galaxy_info:
  role_name: kubeadm_setup
  author: Felipe Rocha
  description: Install and preconfigure kubeadm
  company: Raipe Systems

  license: MIT

  min_ansible_version: 2.10

  platforms:
  - name: Ubuntu
    versions:
    - 18.04
    - 20.04
    
  galaxy_tags:
    - kubeamd
    - k8s
    - ubuntu
    - install
    - configure

dependencies: []